[package]
name = "docker-run"
version = "1.5.0"
authors = ["Petter Rasmussen <petter@hask.no>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "1.5.0"
httparse = "1.10.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
iowrap = "0.2.1"
log = "0.4.34"
env_logger = "0.11.11"
actix-web = "4.15.0"
